#!/bin/bash
#
# Author: This script is used to send local files to different servers

HOSTS=('localhost' '111.11.11.1' '123.123.122.11')

for host in ${HOSTS[@]};
do
	scp -P 2228 filename.txt user@$host > /dev/null 2>&1
	if [[ $? -eq 0 ]]; then
		echo "File send successfully to server $host"
	else
		echo "Error sending file to remote server $host"
	fi

	echo $host
done


